Fix compilation under newer GCC/Clang
Linking coreclr with gcc 10 or clang 11 (both of which default to
-fno-common) fails with this error:

    [31%] Linking CXX shared library libdbgshim.so
    /usr/bin/ld: ../../pal/src/libcoreclrpal.a(dyn-info-list.c.o):src/pal/src/libunwind/src/mi/dyn-info-list.c:28:
    multiple definition of `_U_dyn_info_list'; ../../pal/src/libcoreclrpal.a(Linit.c.o):src/pal/src/libunwind/src/x86_64/Ginit.c:52:
    first defined here

This commit fixes that, by switching to -fcommon as the default.