AggregateException: Use StringBuilder.AppendFormat
Use `AppendFormat(...)` instead of `Append(string.Format(...))` and
`AppendLine()` instead of `Append(Environment.NewLine)`.